# Cloud Build configuration for Timesheet MCP Server
#
# This configuration:
# 1. Builds Docker image using multi-stage Dockerfile
# 2. Pushes to Google Artifact Registry
# 3. Deploys to Cloud Run
#
# Prerequisites:
# 1. Enable Cloud Build and Cloud Run APIs
# 2. Create Artifact Registry repository:
#    gcloud artifacts repositories create timesheet --repository-format=docker --location=europe-west1
# 3. Grant Cloud Build service account Cloud Run Admin role
# 4. Connect GitHub repository to Cloud Build trigger
#
# Environment variables to set in Cloud Run (via substitutions or console):
# - MCP_SERVER_URL: Your Cloud Run service URL (e.g., https://mcp.timesheet.io)
# - MCP_ENDPOINT_PATH: / (recommended for clean URLs)
# - TIMESHEET_API_TOKEN: API key (use Secret Manager for production)

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: timesheet-mcp
  _REPOSITORY: timesheet
  _MCP_SERVER_URL: https://timesheet-mcp-HASH.run.app  # Update after first deploy or use custom domain

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '.'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      # Resource configuration
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300'
      - '--concurrency=80'
      - '--min-instances=0'
      - '--max-instances=10'
      # Environment variables
      - '--set-env-vars=MCP_ENDPOINT_PATH=/'
      - '--set-env-vars=MCP_SERVER_URL=${_MCP_SERVER_URL}'
      - '--set-env-vars=NODE_ENV=production'
      # Uncomment to use Secret Manager for API token:
      # - '--set-secrets=TIMESHEET_API_TOKEN=timesheet-api-token:latest'

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Faster builds
